-- MySQL Script generated by MySQL Workbench
-- Mon Oct  7 14:18:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empregado_projeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empregado_projeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empregado_projeto` DEFAULT CHARACTER SET utf8 ;
USE `empregado_projeto` ;

-- -----------------------------------------------------
-- Table `empregado_projeto`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empregado_projeto`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empregado_projeto`.`Empregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empregado_projeto`.`Empregado` (
  `idEmpregado` INT NOT NULL AUTO_INCREMENT,
  `Matricula` VARCHAR(10) NOT NULL,
  `Nome` VARCHAR(200) NOT NULL,
  `Salario` DECIMAL(2) NOT NULL,
  `Rua` VARCHAR(100) NOT NULL,
  `Bairro` VARCHAR(100) NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idEmpregado`),
  -- INDEX `fk_Empregado_Departamento1_idx` (`Departamento_idDepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_Empregado_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `empregado_projeto`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empregado_projeto`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empregado_projeto`.`Projeto` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Localizacao` VARCHAR(100) NULL,
  PRIMARY KEY (`idProjeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empregado_projeto`.`Dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empregado_projeto`.`Dependente` (
  `NomeDependente` VARCHAR(45) NOT NULL,
  `Sexo` CHAR NULL,
  `DataNasc` DATE NOT NULL,
  `Parentesco` VARCHAR(45) NOT NULL,
  `Empregado_idEmpregado` INT NOT NULL,
  PRIMARY KEY (`NomeDependente`),
  -- INDEX `fk_Dependente_Empregado1_idx` (`Empregado_idEmpregado` ASC) VISIBLE,
  CONSTRAINT `fk_Dependente_Empregado1`
    FOREIGN KEY (`Empregado_idEmpregado`)
    REFERENCES `empregado_projeto`.`Empregado` (`idEmpregado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empregado_projeto`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empregado_projeto`.`Telefone` (
  `Empregado_idEmpregado` INT NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Telefone`, `Empregado_idEmpregado`),
  -- INDEX `fk_Telefone_Empregado1_idx` (`Empregado_idEmpregado` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Empregado1`
    FOREIGN KEY (`Empregado_idEmpregado`)
    REFERENCES `empregado_projeto`.`Empregado` (`idEmpregado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empregado_projeto`.`Empregado_has_Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empregado_projeto`.`Empregado_has_Projeto` (
  `Empregado_idEmpregado` INT NOT NULL,
  `Projeto_idProjeto` INT NOT NULL,
  PRIMARY KEY (`Empregado_idEmpregado`, `Projeto_idProjeto`),
  -- INDEX `fk_Empregado_has_Projeto_Projeto1_idx` (`Projeto_idProjeto` ASC) VISIBLE,
  -- INDEX `fk_Empregado_has_Projeto_Empregado_idx` (`Empregado_idEmpregado` ASC) VISIBLE,
  CONSTRAINT `fk_Empregado_has_Projeto_Empregado`
    FOREIGN KEY (`Empregado_idEmpregado`)
    REFERENCES `empregado_projeto`.`Empregado` (`idEmpregado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empregado_has_Projeto_Projeto1`
    FOREIGN KEY (`Projeto_idProjeto`)
    REFERENCES `empregado_projeto`.`Projeto` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
